# Comprehensive mushroom dictionary mapping common names to Wikipedia pages
MUSHROOM_MAPPINGS = {
    'shiitake': 'Shiitake',
    'oyster': 'Oyster_mushroom',
    'portobello': 'Portobello_mushroom',
    'chanterelle': 'Chanterelle',
    'morel': 'Morchella',
    'porcini': 'Boletus_edulis',
    'enoki': 'Enokitake',
    'maitake': 'Maitake',
    'lion\'s mane': 'Hericium_erinaceus',
    'lions mane': 'Hericium_erinaceus',
    'reishi': 'Ganoderma_lucidum',
    'cremini': 'Agaricus_bisporus',
    'button': 'Agaricus_bisporus',
    'matsutake': 'Matsutake',
    'honey': 'Armillaria',
    'truffle': 'Truffle',
    'puffball': 'Puffball',
    'white button': 'Agaricus_bisporus',
    'king oyster': 'Pleurotus_eryngii',
    'beech': 'Hypsizygus_tessellatus',
    'shimeji': 'Hypsizygus_tessellatus',
    'nameko': 'Pholiota_nameko',
    'wood ear': 'Auricularia_auricula-judae',
    'black trumpet': 'Craterellus_cornucopioides',
    'hedgehog': 'Hydnum_repandum',
    'chicken of the woods': 'Laetiporus',
    'hen of the woods': 'Grifola_frondosa',
    'turkey tail': 'Trametes_versicolor',
    'wine cap': 'Stropharia_rugosoannulata',
    'blewit': 'Clitocybe_nuda',
    'field mushroom': 'Agaricus_campestris',
    'meadow mushroom': 'Agaricus_campestris',
    'parasol': 'Macrolepiota_procera',
    'liberty cap': 'Psilocybe_semilanceata',
    'magic mushroom': 'Psilocybe_cubensis',
    'golden teacher': 'Psilocybe_cubensis',
    'blue meanie': 'Panaeolus_cyanescens',
    'amanita': 'Amanita',
    'fly agaric': 'Amanita_muscaria',
    'death cap': 'Amanita_phalloides',
    'destroying angel': 'Amanita_bisporigera',
    'false morel': 'Gyromitra_esculenta',
    'jack o\'lantern': 'Omphalotus_nidiformis',
    'green spored lepiota': 'Chlorophyllum_molybdites',
    'deadly galerina': 'Galerina_marginata',
    'panther cap': 'Amanita_pantherina',
    'fool\'s mushroom': 'Amanita_verna',
    'webcap': 'Cortinarius',
    'funeral bell': 'Galerina_marginata',
    'artist\'s conk': 'Ganoderma_applanatum',
    'tinder fungus': 'Fomes_fomentarius',
    'birch polypore': 'Fomitopsis_betulina',
    'red belt conk': 'Fomitopsis_pinicola',
    'dryad\'s saddle': 'Polyporus_squamosus',
    'oyster bracket': 'Pleurotus_ostreatus',
    'sulphur shelf': 'Laetiporus_sulphureus',
    'chaga': 'Inonotus_obliquus',
    'razor strop': 'Piptoporus_betulinus',
    'orange peel': 'Aleuria_aurantia',
    'scarlet cup': 'Sarcoscypha_austriaca',
    'coral fungus': 'Ramaria',
    'crown coral': 'Artomyces_pyxidatus',
    'cauliflower': 'Sparassis_crispa',
    'inky cap': 'Coprinus_comatus',
    'shaggy mane': 'Coprinus_comatus',
    'fairy ring': 'Marasmius_oreades',
    'milk cap': 'Lactarius',
    'russula': 'Russula',
    'brittlegill': 'Russula',
    'wax cap': 'Hygrocybe',
    'violet webcap': 'Cortinarius_violaceus',
    'gypsy mushroom': 'Cortinarius_caperatus',
    'blusher': 'Amanita_rubescens',
    'grisette': 'Amanita_vaginata',
    'honey mushroom': 'Armillaria_mellea',
    'velvet foot': 'Flammulina_velutipes',
    'winter mushroom': 'Flammulina_velutipes',
    'brick cap': 'Hypholoma_lateritium',
    'sulfur tuft': 'Hypholoma_fasciculare',
    'laughing gym': 'Gymnopilus_junonius',
    'big laughing gym': 'Gymnopilus_spectabilis',
    'bay bolete': 'Imleria_badia',
    'slippery jack': 'Suillus_luteus',
    'old man of the woods': 'Strobilomyces_strobilaceus',
    'red cracked bolete': 'Xerocomellus_chrysenteron',
    'bitter bolete': 'Tylopilus_felleus',
    'devil\'s bolete': 'Rubroboletus_satanas',
    'two colored bolete': 'Baorangia_bicolor',
    'butter bolete': 'Butyriboletus_appendiculatus',
    'turkey tail': 'Trametes_versicolor',
    'false turkey tail': 'Stereum_ostrea',
    'violet toothed polypore': 'Trichaptum_biforme',
    'thin maze flat polypore': 'Daedaleopsis_confragosa',
    'gilled polypore': 'Lenzites_betulina',
    'smoky polypore': 'Bjerkandera_adusta',
    'orange mock oyster': 'Phyllotopsis_nidulans',
    'wood ear': 'Auricularia_auricula-judae',
    'witches butter': 'Tremella_mesenterica',
    'orange jelly': 'Dacrymyces_palmatus',
    'crystal brain': 'Myxarium_nucleatum',
    'purple jelly drops': 'Ascocoryne_sarcoides',
    'stinkhorn': 'Phallus_impudicus',
    'dog stinkhorn': 'Mutinus_elegans',
    'basket stinkhorn': 'Ileodictyon_cibarium',
    'octopus stinkhorn': 'Clathrus_archeri',
    'red cage': 'Clathrus_ruber',
    'earthball': 'Scleroderma_citrinum',
    'giant puffball': 'Calvatia_gigantea',
    'pear shaped puffball': 'Lycoperdon_pyriforme',
    'gem studded puffball': 'Lycoperdon_perlatum',
    'devil\'s urn': 'Urnula_craterium',
    'bleeding tooth': 'Hydnellum_peckii',
    'violet coral': 'Clavaria_zollingeri',
    'dead man\'s fingers': 'Xylaria_polymorpha',
    'carbon balls': 'Kretzschmaria_deusta',
    'bird\'s nest fungus': 'Crucibulum_laeve',
    'split gill': 'Schizophyllum_commune',
    'wrinkled peach': 'Rhodotus_palmatus',
    'blue green mold': 'Penicillium',
    'green mold': 'Trichoderma',
    'pink mold': 'Neurospora_crassa'
}
